Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Naming/PredicateName:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - '≤'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
