Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/AsciiComments:
  AllowedChars:
    - '≤'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
